### ISSUE TITLE
Phần search show kết quả search chứa các ký tự trong bài viết

### ISSUE THREAD

**Issue by golddessun** [RedditVN/redditvn-react#5]
Steps to reproduce:
1. Click vào khung search và đánh dấu ;
![image](https://user-images.githubusercontent.com/2587351/33971894-d195c476-e048-11e7-9c25-ede452eee540.png)
2. Enter và search

Actual result:
- Search ra những bài viết chứa ký tự trong khu search
![image](https://user-images.githubusercontent.com/2587351/33971908-f5a692d2-e048-11e7-91f9-8e47af7bbc90.png)

Expected result:
- Mình đề nghị nếu có thể thì chỉ nên search theo tag, vd r/NSFW hoặc theo tên bài viết

**Comment by tdtgit** [comment]
Mềnh thấy bộ search như vậy là mạnh và hợp lý ấy chứ. Đôi khi có người chỉ nhớ một phần nào đó, hoặc sub, hoặc tên bài viết, hoặc nội dung bài viết thôi.

**Comment by golddessun** [comment]
theo mình thì nó không thân thiện cho lắm tại nếu chỉ search 1 hoặc 2 cụm từ nhưng lại ra quá nhiều kết quả thì nó không hay lắm. Giả sử bài ít thì không sao, chứ mà lên cả trăm cả ngàn bài thì không ổn á. Cái này là mình dựa theo kinh nghiệm từ những requirement mình đã làm nên mình góp ý thôi

**Comment by sontrinh** [comment]
Search box hỗ trợ regex nếu bạn muốn search nâng cao: `regex:<Regular Expression>`
